name = "anita-invoice-tracker-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "anita-invoice-tracker"
database_id = "d852a373-d2e7-496f-b08f-2ba20d588189"
